/**
 * Generated route tree (placeholder)
 * 
 * This file will be auto-generated by TanStack Router plugin
 * For now, providing manual structure
 */
import { createRoute, createRootRoute } from '@tanstack/react-router'

const rootRoute = createRootRoute()

const indexRoute = createRoute({
  getParentRoute: () => rootRoute,
  path: '/',
})

export const routeTree = rootRoute.addChildren([indexRoute])
